import {useEffect,useState} from 'react';
import Notebook from './notebook';
import {rememberedDirectory,openDirectory,chooseDirectory,supported,useBrowser,type Directory} from '@/lib/vault-storage';
export default function LocalNotebook(){
 const [name,setName]=useState<string|null>(null),[directory,setDirectory]=useState<Directory|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState(''),[session,setSession]=useState(0);
 useEffect(()=>{void (async()=>{try{if(!supported()){await useBrowser();setName('Stockage du navigateur');return}const remembered=await rememberedDirectory();setDirectory(remembered);if(remembered&&await remembered.queryPermission({mode:'readwrite'})==='granted')setName(await openDirectory(remembered));}catch(e){setError((e as Error).message)}finally{setBusy(false)}})()},[]);
 async function choose(){setBusy(true);setError('');try{setName(await chooseDirectory());setDirectory(await rememberedDirectory());setSession(s=>s+1)}catch(e){if(!(e instanceof DOMException&&e.name==='AbortError'))setError((e as Error).message)}finally{setBusy(false)}}
 async function authorize(){if(!directory)return;setBusy(true);try{if(await directory.requestPermission({mode:'readwrite'})!=='granted')throw new Error('Autorisez l’accès pour ouvrir ce carnet.');setName(await openDirectory(directory));setSession(s=>s+1);setError('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <>{error&&<div className="error" role="alert">{error}</div>}{name?<Notebook key={session} folderName={name} onSwitch={choose} onAuthorize={directory?authorize:undefined} switching={busy} canChooseFolder={supported()}/>:<main className="wrap"><h1>Ouvrir un carnet local</h1><section className="panel"><p>Choisissez le dossier où conserver vos personnages, vos événements et vos photos. Un dossier existant ouvre son carnet ; un dossier vide démarre un nouveau carnet.</p>{directory&&<button className="btn primary" disabled={busy} onClick={authorize}>Autoriser le dossier {directory.name}</button>}<button className="btn" disabled={busy} onClick={choose}>Choisir un dossier</button><p>Ce choix sera mémorisé dans ce navigateur. Aucun compte requis. Toutes les données restent locales.</p></section></main>}</>;
}
